GET http://localhost:5000/product

###

GET http://localhost:5000/product/1

###

GET http://localhost:5000/product/1/price

###

POST http://localhost:5000/order

###
POST http://localhost:5000/api/payment/process-transactions


###
POST http://localhost:1500/api/start?mode=print&password=8uNiXR7dqX549jjG

