GET http://localhost:5000/product

###

GET http://localhost:5000/product/1

###

GET http://localhost:5000/product/1/price

###

POST http://localhost:5000/order

###
POST http://localhost:5000/api/payment/process-transactions

###
POST http://localhost:5000/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="frame-image.png"
Content-Type: image/jpeg

[Binary data of the image file]
----WebKitFormBoundary7MA4YWxkTrZu0gW--




###6f12ddd3-604e-4921-ad8d-f2a0833be6af

GET http://localhost:5000/api/payment/get-transaction-status/:orderId


###
POST http://localhost:1500/api/start?mode=print&password=8uNiXR7dqX549jjG

###
PUT http://localhost:5000/order/update-status
Content-Type: application/json

{
    "newStatus": "ss"
}

